"""Curated stock universes for screening — S&P 500 (US) + Nifty 500 (India)."""

# US: S&P 500 constituents (large/mid-cap)
US_UNIVERSE = [
    "MMM","AOS","ABT","ABBV","ACN","ADBE","AMD","AES","AFL","A","APD","ABNB","AKAM","ALB","ARE","ALGN","ALLE","LNT","ALL","GOOGL","GOOG","MO","AMZN","AMCR","AEE","AAL","AEP","AXP","AIG","AMT","AWK","AMP","AME","AMGN","APH","ADI","ANSS","AON","APA","AAPL","AMAT","APTV","ACGL","ADM","ANET","AJG","AIZ","T","ATO","ADSK","ADP","AZO","AVB","AVY","AXON","BKR","BALL","BAC","BAX","BDX","BRK-B","BBY","TECH","BIIB","BLK","BX","BK","BA","BKNG","BWA","BSX","BMY","AVGO","BR","BRO","BF-B","BLDR","BG","BXP","CHRW","CDNS","CZR","CPT","CPB","COF","CAH","KMX","CCL","CARR","CTLT","CAT","CBOE","CBRE","CDW","CE","COR","CNC","CNP","CF","CHRD","CRL","SCHW","CHTR","CVX","CMG","CB","CHD","CI","CINF","CTAS","CSCO","C","CFG","CLX","CME","CMS","KO","CTSH","CL","CMCSA","CAG","COP","ED","STZ","CEG","COO","CPRT","GLW","CPAY","CTVA","CSGP","COST","CTRA","CRWD","CCI","CSX","CMI","CVS","DHR","DRI","DVA","DAY","DECK","DE","DAL","DVN","DXCM","FANG","DLR","DFS","DG","DLTR","D","DPZ","DOV","DOW","DHI","DTE","DUK","DD","EMN","ETN","EBAY","ECL","EIX","EW","EA","ELV","EMR","ENPH","ETR","EOG","EPAM","EQT","EFX","EQIX","EQR","ESS","EL","ETSY","EG","EVRG","ES","EXC","EXPE","EXPD","EXR","XOM","FFIV","FDS","FICO","FAST","FRT","FDX","FIS","FITB","FSLR","FE","FI","FMC","F","FTNT","FTV","FOXA","FOX","BEN","FCX","GRMN","IT","GE","GEHC","GEV","GEN","GNRC","GD","GIS","GM","GPC","GILD","GPN","GL","GS","HAL","HIG","HAS","HCA","DOC","HSIC","HSY","HES","HPE","HLT","HOLX","HD","HON","HRL","HST","HWM","HPQ","HUBB","HUM","HBAN","HII","IBM","IEX","IDXX","ITW","ILMN","INCY","IR","PODD","INTC","ICE","IFF","IP","IPG","INTU","ISRG","IVZ","INVH","IQV","IRM","JBHT","JBL","JKHY","J","JNJ","JCI","JPM","JNPR","K","KVUE","KDP","KEY","KEYS","KMB","KIM","KMI","KKR","KLAC","KHC","KR","LHX","LH","LRCX","LW","LVS","LDOS","LEN","LIN","LYV","LKQ","LMT","L","LOW","LULU","LYB","MTB","MPC","MKTX","MAR","MMC","MLM","MAS","MA","MTCH","MKC","MCD","MCK","MDT","MRK","META","MET","MTD","MGM","MCHP","MU","MSFT","MAA","MRNA","MHK","MOH","TAP","MDLZ","MPWR","MNST","MCO","MS","MOS","MSI","MSCI","NDAQ","NTAP","NFLX","NEM","NWSA","NWS","NEE","NKE","NI","NDSN","NSC","NTRS","NOC","NCLH","NRG","NUE","NVDA","NVR","NXPI","ORLY","OXY","ODFL","OMC","ON","OKE","ORCL","OTIS","PCAR","PKG","PLTR","PANW","PARA","PH","PAYX","PAYC","PYPL","PNR","PEP","PFE","PCG","PM","PSX","PNW","PNC","POOL","PPG","PPL","PFG","PG","PGR","PLD","PRU","PEG","PTC","PSA","PHM","QRVO","PWR","QCOM","DGX","RL","RJF","RTX","O","REG","REGN","RF","RSG","RMD","RVTY","ROK","ROL","ROP","ROST","RCL","SPGI","CRM","SBAC","SLB","STX","SRE","NOW","SHW","SPG","SWKS","SJM","SW","SNA","SOLV","SO","LUV","SWK","SBUX","STT","STLD","STE","SYK","SMCI","SYF","SNPS","SYY","TMUS","TROW","TTWO","TPR","TRGP","TGT","TEL","TDY","TFX","TER","TSLA","TXN","TPL","TXT","TMO","TJX","TKO","TSCO","TT","TDG","TRV","TRMB","TFC","TYL","TSN","USB","UBER","UDR","ULTA","UNP","UAL","UPS","URI","UNH","UHS","VLO","VTR","VLTO","VRSN","VRSK","VZ","VRTX","VTRS","V","VST","VMC","WRB","GWW","WAB","WBA","WMT","DIS","WBD","WM","WAT","WEC","WFC","WELL","WST","WDC","WY","WMB","WTW","WDAY","WYNN","XEL","XYL","YUM","ZBRA","ZBH","ZTS"
]

US_INDICES = {
    "^GSPC": "S&P 500",
    "^IXIC": "NASDAQ",
    "^DJI": "Dow Jones",
    "^RUT": "Russell 2000",
    "^VIX": "VIX",
}

# India: Nifty 500 constituents (NSE) — covers all major large/mid/small caps
IN_UNIVERSE = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","BHARTIARTL.NS","ICICIBANK.NS","INFY.NS","SBIN.NS","LT.NS","HINDUNILVR.NS","ITC.NS",
    "BAJFINANCE.NS","KOTAKBANK.NS","HCLTECH.NS","AXISBANK.NS","MARUTI.NS","ASIANPAINT.NS","M&M.NS","SUNPHARMA.NS","TITAN.NS","ULTRACEMCO.NS",
    "ADANIENT.NS","NTPC.NS","ONGC.NS","POWERGRID.NS","WIPRO.NS","TATAMOTORS.NS","JSWSTEEL.NS","BAJAJFINSV.NS","NESTLEIND.NS","TATASTEEL.NS",
    "COALINDIA.NS","HDFCLIFE.NS","GRASIM.NS","BAJAJ-AUTO.NS","ADANIPORTS.NS","BPCL.NS","DRREDDY.NS","EICHERMOT.NS","BRITANNIA.NS","CIPLA.NS",
    "HEROMOTOCO.NS","DIVISLAB.NS","INDUSINDBK.NS","TECHM.NS","APOLLOHOSP.NS","TATACONSUM.NS","SBILIFE.NS","HINDALCO.NS","SHRIRAMFIN.NS","LTIM.NS",
    "DMART.NS","PIDILITIND.NS","DLF.NS","ZOMATO.NS","TRENT.NS","VEDL.NS","GODREJCP.NS","SIEMENS.NS","HAVELLS.NS","AMBUJACEM.NS",
    "BANKBARODA.NS","PNB.NS","CANBK.NS","IRCTC.NS","IRFC.NS","BEL.NS","HAL.NS","BHEL.NS","GAIL.NS","IOC.NS",
    "PFC.NS","RECLTD.NS","TVSMOTOR.NS","MOTHERSON.NS","BOSCHLTD.NS","ABB.NS","ABBOTINDIA.NS","ABCAPITAL.NS","ABFRL.NS","ACC.NS",
    "ADANIGREEN.NS","ADANIPOWER.NS","ATGL.NS","AUBANK.NS","AUROPHARMA.NS","APLAPOLLO.NS","ALKEM.NS","AMARAJABAT.NS","ASHOKLEY.NS","ASTRAL.NS",
    "ATUL.NS","BAJAJHLDNG.NS","BALKRISIND.NS","BANDHANBNK.NS","BANKINDIA.NS","BATAINDIA.NS","BERGEPAINT.NS","BIOCON.NS","BSOFT.NS","CHOLAFIN.NS",
    "CHOLAHLDNG.NS","COFORGE.NS","COLPAL.NS","CONCOR.NS","COROMANDEL.NS","CROMPTON.NS","CUMMINSIND.NS","CYIENT.NS","DABUR.NS","DALBHARAT.NS",
    "DEEPAKNTR.NS","DIXON.NS","ESCORTS.NS","EXIDEIND.NS","FEDERALBNK.NS","FORTIS.NS","GLAND.NS","GLAXO.NS","GLENMARK.NS","GMRINFRA.NS",
    "GMRP&UI.NS","GODREJPROP.NS","GUJGASLTD.NS","HDFCAMC.NS","HONAUT.NS","ICICIGI.NS","ICICIPRULI.NS","IDEA.NS","IDFCFIRSTB.NS","IGL.NS",
    "INDHOTEL.NS","INDIGO.NS","IPCALAB.NS","JINDALSTEL.NS","JSWENERGY.NS","JUBLFOOD.NS","LALPATHLAB.NS","LICHSGFIN.NS","LICI.NS","LUPIN.NS",
    "MFSL.NS","MARICO.NS","MAXHEALTH.NS","MCDOWELL-N.NS","MGL.NS","MINDTREE.NS","MPHASIS.NS","MUTHOOTFIN.NS","NMDC.NS","OBEROIRLTY.NS",
    "OFSS.NS","PAGEIND.NS","PEL.NS","PERSISTENT.NS","PETRONET.NS","PIIND.NS","POLICYBZR.NS","POLYCAB.NS","PRESTIGE.NS","RAJESHEXPO.NS",
    "RAMCOCEM.NS","RBLBANK.NS","RVNL.NS","SAIL.NS","SBICARD.NS","SCHAEFFLER.NS","SHREECEM.NS","SONACOMS.NS","SRF.NS","STAR.NS",
    "SUNDARMFIN.NS","SUNTV.NS","SUPREMEIND.NS","SYNGENE.NS","TATACHEM.NS","TATACOMM.NS","TATAELXSI.NS","TATAPOWER.NS","TIINDIA.NS","TORNTPHARM.NS",
    "TORNTPOWER.NS","TVSHLTD.NS","UBL.NS","UNIONBANK.NS","UPL.NS","VBL.NS","VOLTAS.NS","WHIRLPOOL.NS","YESBANK.NS","ZEEL.NS",
    "ZYDUSLIFE.NS","3MINDIA.NS","AARTIIND.NS","AAVAS.NS","ABSLAMC.NS","ACI.NS","ADANIWILMAR.NS","AEGISCHEM.NS","AFFLE.NS","AIAENG.NS",
    "AJANTPHARM.NS","AKZOINDIA.NS","ALKYLAMINE.NS","ALOKINDS.NS","AMBER.NS","ANGELONE.NS","ANURAS.NS","APARINDS.NS","APOLLOTYRE.NS","APTUS.NS",
    "ARCHIDPLY.NS","ARVIND.NS","ASAHIINDIA.NS","ASTERDM.NS","ASTRAZEN.NS","ATFL.NS","AUTOAXLES.NS","AVANTIFEED.NS","BAJAJELEC.NS","BALAMINES.NS",
    "BALMLAWRIE.NS","BALRAMCHIN.NS","BASF.NS","BAYERCROP.NS","BBTC.NS","BDL.NS","BEML.NS","BHARATFORG.NS","BIRLACORPN.NS","BLISSGVS.NS",
    "BLUEDART.NS","BLUESTARCO.NS","BORORENEW.NS","BSE.NS","CAMS.NS","CANFINHOME.NS","CAPLIPOINT.NS","CAPLPL.NS","CARBORUNIV.NS","CARERATING.NS",
    "CASTROLIND.NS","CCL.NS","CDSL.NS","CENTRALBK.NS","CENTURYTEX.NS","CERA.NS","CESC.NS","CGCL.NS","CGPOWER.NS","CHALET.NS",
    "CHAMBLFERT.NS","CHENNPETRO.NS","CIEINDIA.NS","CLEAN.NS","CMSINFO.NS","COCHINSHIP.NS","COFFEEDAY.NS","COMPUTEAGE.NS","CRAFTSMAN.NS","CREDITACC.NS",
    "CRISIL.NS","CSBBANK.NS","CUB.NS","DBL.NS","DCBBANK.NS","DCMSHRIRAM.NS","DEEPAKFERT.NS","DELHIVERY.NS","DELTACORP.NS","DEVYANI.NS",
    "DHANI.NS","DHANUKA.NS","DIAMONDYD.NS","DIVGIITTS.NS","DREDGECORP.NS","EASEMYTRIP.NS","ECLERX.NS","EDELWEISS.NS","EICHERMOT.NS","EIDPARRY.NS",
    "EIHOTEL.NS","ELECON.NS","ELGIEQUIP.NS","ENGINERSIN.NS","EPL.NS","ERIS.NS","FACT.NS","FDC.NS","FINCABLES.NS","FINEORG.NS",
    "FINPIPE.NS","FIVESTAR.NS","FLUOROCHEM.NS","FSL.NS","GAEL.NS","GALAXYSURF.NS","GANECOS.NS","GARFIBRES.NS","GESHIP.NS","GICRE.NS",
    "GILLETTE.NS","GMDCLTD.NS","GMMPFAUDLR.NS","GNFC.NS","GOCOLORS.NS","GODFRYPHLP.NS","GODREJAGRO.NS","GODREJIND.NS","GPIL.NS","GPPL.NS",
    "GRANULES.NS","GRAPHITE.NS","GRINDWELL.NS","GRSE.NS","GSFC.NS","GSPL.NS","GUJALKALI.NS","HAPPYFORGE.NS","HATHWAY.NS","HATSUN.NS",
    "HBLPOWER.NS","HEG.NS","HEIDELBERG.NS","HEMIPROP.NS","HFCL.NS","HGS.NS","HIKAL.NS","HIL.NS","HINDCOPPER.NS","HINDPETRO.NS",
    "HINDZINC.NS","HOMEFIRST.NS","HUDCO.NS","IBULHSGFIN.NS","IBREALEST.NS","ICRA.NS","IDBI.NS","IDFC.NS","IEX.NS","IFBIND.NS",
    "IIFL.NS","IIFLSEC.NS","INDIACEM.NS","INDIAMART.NS","INDIANB.NS","INDOCO.NS","INFIBEAM.NS","INGERRAND.NS","INOXLEISUR.NS","INTELLECT.NS",
    "IOB.NS","ISGEC.NS","ISEC.NS","ITDC.NS","JBCHEPHARM.NS","JINDALSAW.NS","JKCEMENT.NS","JKLAKSHMI.NS","JKPAPER.NS","JKTYRE.NS",
    "JMFINANCIL.NS","JSL.NS","JSWHL.NS","JSWINFRA.NS","JUBLINGREA.NS","JUBLPHARMA.NS","JUSTDIAL.NS","JYOTHYLAB.NS","KAJARIACER.NS","KALYANKJIL.NS",
    "KANSAINER.NS","KARURVYSYA.NS","KEC.NS","KEI.NS","KFINTECH.NS","KIRLOSBROS.NS","KIRLOSENG.NS","KIRLOSIND.NS","KNRCON.NS","KPITTECH.NS",
    "KPRMILL.NS","KRBL.NS","KSB.NS","LATENTVIEW.NS","LAURUSLABS.NS","LAXMIMACH.NS","LEMONTREE.NS","LINDEINDIA.NS","LLOYDSME.NS","LTF.NS",
    "LTTS.NS","LUXIND.NS","MAHABANK.NS","MAHLIFE.NS","MAHSEAMLES.NS","MANAPPURAM.NS","MANYAVAR.NS","MARKSANS.NS","MASTEK.NS","MAYURUNIQ.NS",
    "MAZDOCK.NS","MEDPLUS.NS","METROBRAND.NS","METROPOLIS.NS","MIDHANI.NS","MINDACORP.NS","MMTC.NS","MOIL.NS","MOTILALOFS.NS","MRF.NS",
    "MRPL.NS","MTARTECH.NS","NATIONALUM.NS","NAUKRI.NS","NAVINFLUOR.NS","NAVNETEDUL.NS","NBCC.NS","NCC.NS","NESCO.NS","NETWORK18.NS",
    "NEWGEN.NS","NFL.NS","NH.NS","NIITLTD.NS","NIITMTS.NS","NLCINDIA.NS","NOCIL.NS","NSLNISP.NS","NUVAMA.NS","NUVOCO.NS",
    "NYKAA.NS","OAL.NS","OFSS.NS","OLECTRA.NS","ORIENTELEC.NS","PAYTM.NS","PCBL.NS","PDSL.NS","PFIZER.NS","PFOCUS.NS",
    "PGHH.NS","PGHL.NS","PIRAMALENT.NS","PNBHOUSING.NS","POLYMED.NS","POLYPLEX.NS","POONAWALLA.NS","POWERINDIA.NS","PPLPHARMA.NS","PRAJIND.NS",
    "PRINCEPIPE.NS","PRSMJOHNSN.NS","PSPPROJECT.NS","PVRINOX.NS","QUESS.NS","RADICO.NS","RAILTEL.NS","RAIN.NS","RAINBOW.NS","RALLIS.NS",
    "RATEGAIN.NS","RATNAMANI.NS","RAYMOND.NS","RCF.NS","REDINGTON.NS","RELAXO.NS","RELIGARE.NS","RENUKA.NS","RHIM.NS","RITES.NS",
    "ROUTE.NS","RRKABEL.NS","RTNINDIA.NS","SAFARI.NS","SANOFI.NS","SAPPHIRE.NS","SCHNEIDER.NS","SHOPERSTOP.NS","SHRIRAMCIT.NS","SHYAMMETL.NS",
    "SIGNATURE.NS","SIS.NS","SJVN.NS","SKFINDIA.NS","SOBHA.NS","SONATSOFTW.NS","SPANDANA.NS","SPARC.NS","STARCEMENT.NS","STARHEALTH.NS",
    "STLTECH.NS","SUDARSCHEM.NS","SUMICHEM.NS","SUNDRMFAST.NS","SUNPHARMA.NS","SUNTECK.NS","SUPRAJIT.NS","SUPREMEIND.NS","SUVENPHAR.NS","SUZLON.NS",
    "SWANENERGY.NS","SWSOLAR.NS","SYMPHONY.NS","SYRMA.NS","TANLA.NS","TASTYBITE.NS","TATAINVEST.NS","TBOTEK.NS","TCI.NS","TCNSBRANDS.NS",
    "TEAMLEASE.NS","TECHNOE.NS","TEGA.NS","THERMAX.NS","THOMASCOOK.NS","THYROCARE.NS","TIPSINDLTD.NS","TITAGARH.NS","TMB.NS","TRIDENT.NS",
    "TRIVENI.NS","TTKPRESTIG.NS","TTML.NS","TVSSCS.NS","UCOBANK.NS","UFLEX.NS","UJJIVAN.NS","UJJIVANSFB.NS","USHAMART.NS","UTIAMC.NS",
    "VAIBHAVGBL.NS","VAKRANGEE.NS","VARROC.NS","VEDL.NS","VENKEYS.NS","VGUARD.NS","VINATIORGA.NS","VIPIND.NS","VISHALMEGA.NS","VRLLOG.NS",
    "VSTIND.NS","WELCORP.NS","WELSPUNIND.NS","WESTLIFE.NS","WOCKPHARMA.NS","ZENSARTECH.NS","ZFCVINDIA.NS","ZYDUSWELL.NS"
]
# De-duplicate within each universe while preserving order
def _dedup(lst):
    seen = set()
    return [s for s in lst if not (s in seen or seen.add(s))]

IN_UNIVERSE = _dedup(IN_UNIVERSE)
US_UNIVERSE = _dedup(US_UNIVERSE)

IN_INDICES = {
    "^NSEI": "Nifty 50",
    "^BSESN": "Sensex",
    "^NSEBANK": "Bank Nifty",
    "^CNXIT": "Nifty IT",
    "^CNXAUTO": "Nifty Auto",
}


def get_universe(market: str):
    return US_UNIVERSE if market.upper() == "US" else IN_UNIVERSE


def get_indices(market: str):
    return US_INDICES if market.upper() == "US" else IN_INDICES


def currency(market: str):
    return "USD" if market.upper() == "US" else "INR"
